### PR TITLE
Added a barebones readme

### PR DESCRIPTION
**Pull request by Not-a-web-Developer**
Next order of business is adding a screenshot and getting this readme reviewed by ben and takase.

### CODE REVIEW

**Comment by benjcollins** [comment]
A much easier way to install this is just to clone the repo into the plugins dir itself then you don't need to make any extra dirs or copy any files. I think the README should show this as the best way of installing the plugin.

**Comment by Not-a-web-Developer** [comment]
> A much easier way to install this is just to clone the repo into the plugins dir itself then you don't need to make any extra dirs or copy any files. I think the README should show this as the best way of installing the plugin.

That's a much better way of installing, I'll add that as the primary way to install in the readme in a couple of hours.

**Comment by Not-a-web-Developer** [comment]
I've fixed the readme, I'll add a screenshot with my crappy nord theme now since I can't get wsl to work rn

**Comment by Not-a-web-Developer** [comment]
@benjcollins the screenshot is added, please check for problems in the readme again and merge it if you don't see any for now.

**Pull request merged**
